/*============================================================
CASO 1: LISTADO DE CLIENTES CON RANGO DE RENTA
============================================================*/
SELECT
    SUBSTR(TO_CHAR(NUMRUT_CLI), 1, LENGTH(TO_CHAR(NUMRUT_CLI)) - 6) || '.' ||
    SUBSTR(TO_CHAR(NUMRUT_CLI), LENGTH(TO_CHAR(NUMRUT_CLI)) - 5, 3) || '.' ||
    SUBSTR(TO_CHAR(NUMRUT_CLI), LENGTH(TO_CHAR(NUMRUT_CLI)) - 2, 3) || '-' || DVRUT_CLI AS "RUT cliente",
    INITCAP(NOMBRE_CLI || ' ' || APPATERNO_CLI || ' ' || APMATERNO_CLI) AS "Nombre Completo Cliente",
    DIRECCION_CLI AS "Dirección Cliente",
    TO_CHAR(ROUND(RENTA_CLI), '$999G999G999') AS "Renta Cliente", 
    SUBSTR('0' || TO_CHAR(CELULAR_CLI), 1, 2) || '-' ||
    SUBSTR('0' || TO_CHAR(CELULAR_CLI), 3, 3) || '-' ||
    SUBSTR('0' || TO_CHAR(CELULAR_CLI), 6, 4) AS "Celular Cliente",
    CASE
        WHEN RENTA_CLI > 500000 THEN 'TRAMO 1'
        WHEN RENTA_CLI BETWEEN 400000 AND 500000 THEN 'TRAMO 2'
        WHEN RENTA_CLI BETWEEN 200000 AND 399999 THEN 'TRAMO 3'
        WHEN RENTA_CLI < 200000 THEN 'TRAMO 4'
    END AS "Tramo Renta Cliente"

FROM CLIENTE
WHERE RENTA_CLI BETWEEN &RENTA_MINIMA AND &RENTA_MAXIMA
    AND CELULAR_CLI IS NOT NULL
ORDER BY INITCAP(NOMBRE_CLI || ' ' || APPATERNO_CLI || ' ' || APMATERNO_CLI);

/*============================================================
CASO 2: SUELDO PROMEDIO POR CATEGORIA DE EMPLEADO
============================================================*/
SELECT
    E.ID_CATEGORIA_EMP AS "CODIGO_CATEGORIA",
    CASE E.ID_CATEGORIA_EMP
        WHEN 1 THEN 'GERENTE'
        WHEN 2 THEN 'SUPERVISOR'
        WHEN 3 THEN 'EJECUTIVO DE ARRIENDO'
        WHEN 4 THEN 'AUXILIAR'
        ELSE 'SIN CATEGORÍA'
    END AS "DESCRIPCION_CATEGORIA",
    COUNT(*) AS "CANTIDAD_EMPLEADOS",
    CASE E.ID_SUCURSAL
        WHEN 10 THEN 'LAS CONDES'
        WHEN 20 THEN 'SANTIAGO CENTRO'
        WHEN 30 THEN 'PROVIDENCIA'
        WHEN 40 THEN 'VITACURA'
        ELSE 'OTRA SUCURSAL'
    END AS "SUCURSAL",
    TO_CHAR(ROUND(AVG(NVL(E.SUELDO_EMP, 0))), '$999G999G999') AS "SUELDO_PROMEDIO"
FROM EMPLEADO E
GROUP BY
    E.ID_CATEGORIA_EMP,
    CASE E.ID_CATEGORIA_EMP
        WHEN 1 THEN 'GERENTE'
        WHEN 2 THEN 'SUPERVISOR'
        WHEN 3 THEN 'EJECUTIVO DE ARRIENDO'
        WHEN 4 THEN 'AUXILIAR'
        ELSE 'SIN CATEGORÍA'
    END,
    CASE E.ID_SUCURSAL
        WHEN 10 THEN 'LAS CONDES'
        WHEN 20 THEN 'SANTIAGO CENTRO'
        WHEN 30 THEN 'PROVIDENCIA'
        WHEN 40 THEN 'VITACURA'
        ELSE 'OTRA SUCURSAL'
    END
HAVING AVG(NVL(E.SUELDO_EMP, 0)) > &SUELDO_PROMEDIO
ORDER BY AVG(NVL(E.SUELDO_EMP, 0)) DESC;

/*============================================================
CASO 3: ARRIENDO PROMEDIO POR TIPO DE PROPIEDAD
============================================================*/
SELECT
    P.ID_TIPO_PROPIEDAD AS "CÓDIGO_TIPO",
    CASE P.ID_TIPO_PROPIEDAD
        WHEN 'A' THEN 'CASA'
        WHEN 'B' THEN 'DEPARTAMENTO'
        WHEN 'C' THEN 'LOCAL'
        WHEN 'D' THEN 'PARCELA SIN CASA'
        WHEN 'E' THEN 'PARCELA CON CASA'
        ELSE 'TIPO DESCONOCIDO'
    END AS "DESCRIPCIÓN_TIPO",
    COUNT(*) AS "TOTAL_PROPIEDADES",
    TO_CHAR(ROUND(AVG(P.VALOR_ARRIENDO)), '$999G999G999') AS "PROMEDIO_ARRIENDO",
    TO_CHAR(ROUND(AVG(P.SUPERFICIE), 2), '99990.00') AS "PROMEDIO_SUPERFICIE",
    TO_CHAR(ROUND(AVG(P.VALOR_ARRIENDO) / AVG(P.SUPERFICIE)), '$999G999G999') AS "VALOR_ARRIENDO_M2",
    CASE
        WHEN (AVG(P.VALOR_ARRIENDO) / AVG(P.SUPERFICIE)) < 5000 THEN 'Económico'
        WHEN (AVG(P.VALOR_ARRIENDO) / AVG(P.SUPERFICIE)) BETWEEN 5000 AND 10000 THEN 'Medio'
        WHEN (AVG(P.VALOR_ARRIENDO) / AVG(P.SUPERFICIE)) > 10000 THEN 'Alto'
    END AS "CLASIFICACIÓN"
FROM PROPIEDAD P
GROUP BY
    P.ID_TIPO_PROPIEDAD,
    CASE P.ID_TIPO_PROPIEDAD
        WHEN 'A' THEN 'CASA'
        WHEN 'B' THEN 'DEPARTAMENTO'
        WHEN 'C' THEN 'LOCAL'
        WHEN 'D' THEN 'PARCELA SIN CASA'
        WHEN 'E' THEN 'PARCELA CON CASA'
        ELSE 'TIPO DESCONOCIDO'
    END
HAVING AVG(P.VALOR_ARRIENDO) / AVG(P.SUPERFICIE) > 1000
ORDER BY "VALOR_ARRIENDO_M2" DESC;